apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsd-demo
  labels:
    app: fsd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsd-demo
  template:
    metadata:
      labels:
        app: fsd-demo
    spec:
      containers:
      - name: fsd-demo-backend
        image: sp1614/fsd-backend-img:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: fsd-demo
